import SchoolSettings from "../components/AdminSettings";

const apiPath = Object.freeze({
  loginadmin: "/admins/auth/login",
  students: "/studetns",
  classes: "/admins/classes/get/all",
  classesByNames:"/admins/classes/classnames",
  createClassess: "/admins/classes/reg",
  updateClass: "/admins/classes/update/class",
  clssToggle: "/admins/classes/class/status",
  getSubjects: "/admins/classes/get/subjects",
  getSubjectsByClassname:"/admins/classes/subjects",
  getSubjectByClassnameSectionWise:"/admins/classes/subjectSection",
  ToggleSubject: "/admins/classes/subject/status",
  createSubject: "/admins/classes/subjects/reg",
  updateSubject: "/admins/classes/update/subject",
  deleteSubject: "/admins/classes/delete/subject",
  getStudents: "/admins/students/get/all",
  getParticularStudent: "/admins/students/get/student/profile",
  studentReg: "/admins/students/reg",
  studentDelete: "/admins/students/delete",
  updateStudent: "/admins/students/update",
  createTeacher: "/admins/teachers/register",
  getTeachers: "/admins/teachers/getAllTeacher",
  getParticularTeacher: "/admins/teachers/getTeacherProfile",
  updateTeacher: "/admins/teachers/update-teacher",
  deleteTeacher: "/admins/teachers/soft-delete",
  getParticularTeacher: "/admins/teachers/get-profile",
  dashboardData: "/admins/dashboard",
  SchoolSettings: "/admins/setting/school-settings",
  createSchoolSettings: "/admins/setting/school-settings",
  updateSchoolSettings: "/admins/setting/update-settings",
  resetSchoolSettings: "/admins/setting/school-settings/reset",
  getAdminProfile: "/admins/auth/profile",
  updateAdminProfile: "/admins/auth/edit-profile",
  createFeesStructure: "/admins/fees/structure",
  getFeesStructure: "/admins/fees/get/fee-structure",
  updateFeesStructure: "/admins/fees/update/fee-structure",
  deleteFeesStructure: "/admins/fees/delete/fee-structure",
  getAllFees: "/admins/fees/get/all",
  feestoggleFeesStructure: "/admins/fees/toggle/status/fee-structure",
  AddFees: "/admins/fees/student",
  getSettings: "admins/setting/school-settings",
  getAssignments: "admins/timetable",
  postAssignmentBulk: "admins/timetable/assign",
  verifyAssignment: "admins/timetable/check",
  resetAssign: "admins/timetable/reset",
  teacherAttendance: "admins/teachers/attendance",
  resetPassword: "admins/auth/forgot-password",
  LinkresetApi: "admins/auth/reset-password",
  TeacherSalary: "admins/teachersalary/salary-status",
  AddClassTeacher: "admins/teachers/class-teacherOf",
  generateTeacherSalary: "/admins/teachersalary/generate-salary",
  importStudents: "/admins/students/bulk-upload",
  getIpAddress: "/admins/ipAddress/getipAddress",
  registerIp: "/admins/ipAddress/register/ipAddress",
  updateIp: "/admins/ipAddress/updateipAddress",
  deleteIp: "/admins/ipAddress/deleteipAddress",
  getHolidays: "/admins/calender/getholidays",
  holidays: "/admins/calender/holidays-calender",
  holidaysUpdate: "/admins/calender/update",
  holidaysDelete: "/admins/calender/delete",
  getAttendanceClockwise: "/admins/teachers/get-all-attendance",
  updateClockwiseAttendance: "/admins/teachers/update-attendance",
  importTeacher: "/admins/teachers/bulk-upload",
  importCalander: "/admins/calender/bulk-upload",
  getallTeachers:"/admins/teachers/allteachers",
  inquiryList:"/admins/auth/contacts",
  galleryCategories:"/admins/setting/get",
  createCategorySetting:"/admins/setting/add",
  deleteCategorySettings:"/admins/setting/delete",
  updateCategorySetting:"/admins/setting/update",
  uploadImageGallery:"/admins/setting/category/upload-images",
  gallerySettingGetImages:"/admins/setting/get-images",
  GallerySettingDeleteImage:"/admins/setting/delete-images",

  // getTeachers:"/admins/teachers/getAllTeacher",
  //   getTeacherDetails:"/admins/teachers/getTeacherProfile",
  //   teacherDelete:"/admins/teachers/soft-delete",
  // updateTeacher:"/admins/teachers/update",
  //   getUsers: "/v1/admin/user",
  //   getUserDetails: "/v1/admin/user/details",
  //   acceptRewardRequest: "v1/admin/rewardRequest/accept",
  //   rejectRewardRequest: "v1/admin/rewardRequest/reject",
  //   getReports: "/v1/admin/report",
  //   rewardRequest: "/v1/admin/rewardRequest",
  //   userProfile: "/v1/user/profile",
  //   updateUser: "/v1/admin/user/edit",
  //   getSubAdmin: "v1/admin/subAdmin",
  //   editSubAdmin: "v1/admin/subAdmin",
  //   bannerDelete: "v1/admin/banner",
  //   getBanner: "v1/admin/banner",
  //   bannerEdit: "v1/admin/banner",
  //   forgetPassword: "/v1/admin/forgot-password",
  //   resetPassword: "/v1/admin/reset-password",
  //   changePassword: "/v1/admin/change-password",
  //   userVerify: "/v1/admin/user/verify",
  //   editProfile: "/v1/admin/edit-profile",
  //   getStaticContent: "/v1/admin/static-content",
  //   updateSettings: "/v1/admin/setting",
  //   emailTemplate: "/v1/admin/email-template",
  //   emailStatus: "/v1/admin/email-template/change-status",
  //   notificationToggle: "/v1/admin/notification-toggle",
  //   changeContentStatus: "/v1/admin/static-content/change-status",
  //   getFAQs: "/v1/admin/faq",
  //   reOrderFaq: "/v1/admin/faq/reOrderFAQ",
  //   searchUsers: "/v1/admin/user/search",
  //   bannerAdd: "/v1/admin/banner",
  //   changeFAQStatus: "/v1/admin/faqs/status",
  //   reportAbuseListing: "v1/admin/report-abuse",
  //   changeStatus: "/v1/admin/change-status",
  //   verficationDetail: "v1/admin/user/verification-details",
  //   notifications: "v1/admin/notification",
  //   getSettings: "/v1/admin/setting",
  //   getUserTransaction: "/v1/admin/transaction/getUserTransaction",
  //   getDashboardDetails: "/v1/admin/dashboard",
  //   earningManagerGraph: "/v1/admin/earningManagerGraph",
  //   addMoneyToUserWallet: "/v1/admin/user/addMoneyToUserWallet",
  //   transactionList: "/v1/admin/transaction/transactionList",
  //   scratchCardHistory: "/v1/admin/scratchCard/history",
  //   addScratchCard: "/v1/admin/scratchCard",
  //   viewScratchCard: "/v1/admin/user/getUserInfo",
  //   addBulkScratchCard: "/v1/admin/scratchCard/generate/bulk-scratch-cards",
  //   depositAmount: "/v1/admin/depositAmount",
  //   supportRequest: "/v1/admin/user/list/supportRequest",
  //   sendFeedbackEmail: "/v1/admin/user/sendFeedbackEmail",
  //   listAddMoneyToUserWallet: "/v1/admin/user/listAddMoneyToUserWallet",
  //   allNotificationUser: "/v1/admin/user/all-users",
  //   approveAndRejectKyc: "/v1/admin/user/kycStatus",
  //   walletTransactionList: "/v1/admin/transaction/getTransactionList",
  //   getAllOffer: "/v1/admin/offer",
  //   getOfferUsers: "/v1/admin/offer/get-offer-users",
  //   downloadCsv: "/v1/admin/offer/csv-download",
  //   generatePreSignUrl: "/v1/admin/generatePreSignedUrl",
  //   category: "/v1/admin/category",
  //   banner: "/v1/admin/banner",
  //   categoryStatus: "/v1/admin/category/status-change",
  //   bannerStatus: "/v1/admin/banner/status-change",
  //   subCategory: "/v1/admin/sub-category",
  //   subCategoryStatus: "/v1/admin/sub-category/status-change",
  //   productStatus: "/v1/admin/product/status-change",
  //   customerStatus: "/v1/admin/user/status-change",
  //   categoryList: "/v1/admin/sub-category/category-list",
  //   customer: "/v1/admin/user",
  //   orders: "/v1/admin/user/orders",
  //   userLogList: "/v1/admin/user/log-list",
  //   product: "/v1/admin/product",
  //   productRating: "/v1/admin/product/rating-list",
  //   countryList: "/v1/admin/country-list",
  //   subCategoryList: "/v1/admin/product/sub-category-list",
  //   reOrderCategory: "/v1/admin/category/re-order",
  //   reOrderCountry: "/v1/admin/country/re-order",
  //   reOrderBanner: "/v1/admin/banner/re-order",
  //   earningList: "/v1/admin/earning",
  //   subscriptionAdd: "/v1/admin/subscription",
  //   subscriptionList: "/v1/admin/subscription",
  //   country:"/v1/admin/country",
  //   countryStatus: "/v1/admin/country/status-change",
  //   countryListData: "/v1/admin/city/country-list",
  //   city: "/v1/admin/city",
  //   cityStatus: "/v1/admin/city/status-change",
  //   language: "/v1/admin/language",
  //   reOrderLanguage: "/v1/admin/language/re-order",
  //   languageStatus: "/v1/admin/language/status-change",
  //   media: "/v1/admin/media",
  //   reOrderMedia: "/v1/admin/media/re-order",
  //   mediaStatus: "/v1/admin/media/status-change",
  //   genre: "/v1/admin/genre",
  //   reOrderGenre: "/v1/admin/genre/re-order",
  //   genreStatus: "/v1/admin/genre/status-change",
  //   changeUserPassword: '/v1/admin/user/change-user-password'
});

export default apiPath;
